### ISSUE TITLE
Wrap and Unwrap tabs should be hidden in deposit mode.

### ISSUE THREAD

**Issue by davidqhr** [HydroProtocol/hydro-sdk#5]
This is an issue in feature/deposit branch.  Since we are using deposit mode, this is no need to show wrap and unwrap tabs any more. 

![image](https://user-images.githubusercontent.com/5846959/56179035-e8b22400-6036-11e9-9472-a3db027b7d24.png)

**Comment by wlchn** [comment]
This is fixed in feature/deposit. https://github.com/HydroProtocol/hydro-sdk-web/commit/73ed783a62d9d05332493bde919e641b76c54ae8
![image](https://user-images.githubusercontent.com/4652410/56181669-0f755800-6041-11e9-9d99-cdb21aceb267.png)
